// export const errorHandler = (fn: any) => async (...args: any) => {
//   try {
//     const { data } = await fn(...args);
//     return { success: true, data };
//   } catch (error: any) {
//     return { success: false, error };
//   }
// };
